/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cirnoworks_libfisce_shell_FisceService */

#ifndef _Included_com_cirnoworks_libfisce_shell_FisceService
#define _Included_com_cirnoworks_libfisce_shell_FisceService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cirnoworks_libfisce_shell_FisceService
 * Method:    execute
 * Signature: (Ljava/nio/ByteBuffer;Lcom/cirnoworks/libfisce/shell/Message;)V
 */
JNIEXPORT void JNICALL Java_com_cirnoworks_libfisce_shell_FisceService_execute
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_cirnoworks_libfisce_shell_FisceService
 * Method:    initContext
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_cirnoworks_libfisce_shell_FisceService_initContext
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cirnoworks_libfisce_shell_FisceService
 * Method:    bootFromClass
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cirnoworks_libfisce_shell_FisceService_bootFromClass
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cirnoworks_libfisce_shell_FisceService
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cirnoworks_libfisce_shell_FisceService_getSize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
