/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cirnoworks_libfisce_shell_VMContext */

#ifndef _Included_com_cirnoworks_libfisce_shell_VMContext
#define _Included_com_cirnoworks_libfisce_shell_VMContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cirnoworks_libfisce_shell_VMContext
 * Method:    execute0
 * Signature: (Ljava/nio/ByteBuffer;)Lcom/cirnoworks/libfisce/shell/Message;
 */
JNIEXPORT jobject JNICALL Java_com_cirnoworks_libfisce_shell_VMContext_execute0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cirnoworks_libfisce_shell_VMContext
 * Method:    initContext0
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_cirnoworks_libfisce_shell_VMContext_initContext0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cirnoworks_libfisce_shell_VMContext
 * Method:    bootFromClass0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cirnoworks_libfisce_shell_VMContext_bootFromClass0
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_cirnoworks_libfisce_shell_VMContext
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cirnoworks_libfisce_shell_VMContext_getSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
